plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

permalink: /:title/

defaults:
    -
        scope:
            path: ""
        values:
            layout: default

url: https://gccgle.github.io/cases/
title: Cases in ConsciousnessBowl
repo: gccgle/cases